### ISSUE TITLE
Read data

### ISSUE THREAD

**Issue by akshar001** [csobrinho/hydroponics#2]
Hello,

This project perfectly identifying the solution to write data.

What if we want to read a data.

**Comment by bradq** [comment]
@akshar001 This project outputs to Google IoT. You can [use their API](https://cloud.google.com/iot/docs/reference/cloudiotdevice/rest) to fetch data programmatically or view it through the GCP console. Retrieval is out of scope of the project as I understand it.

**Comment by csobrinho** [comment]
Yes and no. I have an android app that uses the Firestore API to get the latest data. It also has some Google IoT commands support to enable some pumps, ph, nutrients, etc. I plan to also open source that code but haven't had time to clean it up just yet so early 2021 is my estimate.

I also have a web dashboard using the Google DataStudio that consumes the BigQuery data for a more historical view.

![image](https://user-images.githubusercontent.com/1511758/102416958-a41b2080-3faf-11eb-8298-fde6a8e0e096.png)
![image](https://user-images.githubusercontent.com/1511758/102416933-9bc2e580-3faf-11eb-938e-9d70ab3cb565.png)
